server:
   port: 9090
spring:
  application:
    name: Kafka-Client-Ex
  datasource:
    url: jdbc:h2:file:./data/kf-cloud-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: CONSUMER-CLIENT-EX
      auto-offset-reset: earliest
      max-poll-records: 1
      properties:
        spring.json.trusted.packages: '*'
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.apache.kafka: info
    org.springframework: error
