server:
  port: 8085

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

spring:
  application:
    name: KTS-APP
  datasource:
    url: jdbc:h2:file:./data/KTS-DB
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
    h2:
      console:
        enabled: true
        path: /h2
        settings:
          web-allow-others: false
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#  data:
#    solr:
#      host: http://127.0.0.1:8983/solr
solr:
  host: http://localhost:8983/solr
  username: admin
  password: ENC(D9hrvWJnSvvLZxIkpkUYoNc892j6iYgr)

twitter:
  oauth:
    consumerKey: ENC(YzTARVMN7+Aozz5aL45tqWy7XuvRp1KH2a4Sm5hesqFDV2SjIFqd6w==)
    consumerSecret: ENC(TcCMPH9Ra0fMiHjmavNrgSM/94ZiQT5e1EPEndUXCZT0qImyEB8s/3i7zBFEvJ7hSHgXEzaw/vkYmvhSCQpbMg==)
    accessToken: ENC(yidNsnwPC04QNzwQr1u6PIy4c4PMXSKlrOSldFuGqheUFhLeaUQwaen2RIQRY7DsnpvwTVb32wzpi+nDYp6i9g==)
    accessTokenSecret: ENC(sz6P+CsEJWLAwsfhJWcvA3yMT96wPdf9eVKpi9Ww0IVwGRM2bYgpDTmG6RQrECZqFBzuBWL1UTg=)

